apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: push-trigger
spec:
  bindings:
  - name: branch
    value: $(body.repository.branch)
  - name: url
    value: $(body.repository.url)
  template:
    ref: git-clone-template