apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
  - name: url
    value: $(tt.params.username)
  - name: revision
    default: main
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: git-clone-run-
    spec:
      pipelineRef:
        name: git-clone
      params:
      - name: url
        value: $(tt.params.url)
      - name: branch
        value: $(tt.params.branch)
      workspaces:
      - name: shared-data
        persistentVolumeClaim:
          claimName: tekton-pvc
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
spec: 
  params:
  - name: url
    value: $(body.repository.url)
  - name: branch
    value: $(body.repository.branch)