apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-demo
spec:
  params:
  - name: url
    type: string
  - name: branch
    type: string
  - name: commit
    type: string
  - name: hub
    type: string
  workspaces:
  - name: shared-data
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.url)
      - name: revision
        value: $(params.branch)
      - name: sslVerify
        value: false
    - name: build
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: "$(params.hub):$(params.commit)"
      runAfter:
        - clone
    - name: deploy
      taskRef:
        name: kubernetes-actions
      workspaces:
        - name: manifest-dir
          workspace: shared-data
      params:
      - name: script
        value: |
          sed 's/$IMAGE/$(params.hub):$(params.commit)/g'
          kubectl apply -f ./k8s/deployment.yaml
      runAfter: 
        - build