apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-demo
spec:
  params:
  - name: url
    type: string
  - name: branch
    type: string
  - name: commit
    type: string
  - name: hub
    type: string
  workspaces:
  - name: shared-data
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.url)
      - name: revision
        value: $(params.branch)
      - name: sslVerify
        value: false
    - name: build-fe
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: CONTEXT
          value: "./fe"
        - name: IMAGE
          value: "$(params.hub):$(params.commit)-fe"
      runAfter:
        - clone
    - name: deploy-fe
      taskRef:
        name: kubernetes-actions
      workspaces:
        - name: manifest-dir
          workspace: shared-data
      params:
      - name: script
        value: |
          sed -i 's|PARAM_IMAGE|"$(params.hub):$(params.commit)-fe"|g' ./fe/k8s/deployment.yaml
          kubectl apply -f ./fe/k8s/deployment.yaml
      runAfter: 
        - build-fe
    - name: build-be
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: CONTEXT
          value: "./be"
        - name: IMAGE
          value: "$(params.hub):$(params.commit)-be"
      runAfter:
        - clone
    - name: deploy-be
      taskRef:
        name: kubernetes-actions
      workspaces:
        - name: manifest-dir
          workspace: shared-data
      params:
      - name: script
        value: |
          sed -i 's|PARAM_IMAGE|"$(params.hub):$(params.commit)-be"|g' ./be/k8s/deployment.yaml
          kubectl apply -f ./be/k8s/deployment.yaml
      runAfter: 
        - build-be