apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: trigger-demo
spec:
  bindings:
  - ref: trigger-binding-demo
  - name: url
    value: $(body.repository.url)
  - name: branch
    value: $(body.branch)
  - name: commit
    value: $(body.head_commit.id)
  # - name: script
  #   value: $(body.script)
  template:
    ref: trigger-template-demo
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-demo
spec:
  params:
  - name: url
    default: ""
  - name: branch
    default: main
  - name: commit
    default: commit
  - name: hub
    default: icyou1992/tekton
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipelinerun-demo-
    spec:
      serviceAccountName: robot-demo
      pipelineRef:
        name: pipeline-demo
      podTemplate:
        securityContext:
          fsGroup: 65532
      workspaces:
      - name: shared-data
        persistentVolumeClaim:
          claimName: pvc-demo
      params:
      - name: url
        value: $(tt.params.url)
      - name: branch
        value: $(tt.params.branch)
      - name: commit
        value: $(tt.params.commit)
      - name: hub
        value: $(tt.params.hub)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-demo
spec: 
  params:
  - name: url
    value: $(body.repository.url)
  - name: branch
    value: $(body.repository.default_branch)
  - name: commit
    value: $(body.head_commit.id)
  # - name: script
  #   value: $(body.script)
  
