apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot-demo
secrets:
  - name: auth-ecr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-clusterrolebinding-demo
subjects:
- kind: ServiceAccount
  name: robot-demo
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-rolebinding-demo
subjects:
- kind: ServiceAccount
  name: robot-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
