apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Terraform
  name: aws-auth
  namespace: kube-system
data:
  mapAccounts: |
    []
  mapRoles:
  - groups:
    - system:bootstrappers
    - system:nodes
    rolearn: arn:aws:iam::111122223333:role/my-node-role
    username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []